import random

# THIS PERFORMANCE MATRIX WAS GENERATED BY CHATGPT FOR TIME SAVING.
# NOTHING ELSE IN THIS CODE WAS GENERATED BY AI
# Performance matrix for employees (E1 to E13) across tasks (T1 to T10)
PERFORMANCE_MATRIX = [
    [55, 30, 20, 20, 24, 24, 18, 33, 35, 29],  # E1
    [14, 14, 22, 34, 26, 19, 22, 29, 22, 19],  # E2
    [22, 16, 21, 27, 35, 25, 30, 22, 23, 23],  # E3
    [17, 25, 29, 26, 13, 24, 25, 25, 26, 18],  # E4
    [12, 25, 27, 26, 15, 24, 27, 25, 26, 14],  # E5
    [26, 29, 37, 34, 37, 20, 21, 25, 27, 27],  # E6
    [30, 28, 37, 28, 29, 23, 19, 33, 30, 21],  # E7
    [28, 21, 25, 24, 25, 20, 24, 24, 30, 24],  # E8
    [19, 18, 19, 28, 25, 27, 26, 32, 23, 22],  # E9
    [30, 22, 29, 19, 30, 29, 29, 21, 20, 28],  # E10
    [29, 25, 35, 29, 27, 28, 30, 28, 19, 33],  # E11
    [15, 19, 19, 33, 22, 24, 25, 31, 33, 21],  # E12
    [25, 35, 25, 32, 25, 22, 29, 22, 26, 31]   # E13
]

def fitness_function(assignment :list[int], performance_matrix: list[list[int]] = PERFORMANCE_MATRIX) -> int:
    """
    This function returns the fitness of the indivdual chromosome based on the performance matrix scores. This is used to optimise the algorithm.
    
    Args:
        assignment (list): 1-dimensional list containing which task (index) is performed by which employee (value).
        performance_matrix (list): The 2-dimensional list containing scores for each task-employee combination. Defaults to `PERFORMANCE_MATRIX`.

    Returns:
        int: The overall score of all assignments. 
    """
    # Gets the score from the relevent performance_matrix index and sums them together
    fitness = sum(
        performance_matrix[employee][task] for task, employee in enumerate(assignment)
    )
    return fitness


def chromosome_encoder(performance_matrix: list[list[int]] = PERFORMANCE_MATRIX) -> list[int]:
    """
    Generates a random chromosome where each task is addigned to a unique employee.

    Args: 
        performance_matrix (list, optional): The 2-dimensional list containing scores for each task-employee combination. Defaults to `PERFORMANCE_MATRIX`.

    Returns:
        list: A list of length 10, where each index represents a task and the value represents the assigned employee
    """
    # Select 10 random and unique employees out of the 13
    # This list will represent which employees (value) are assigned to which task (index)
    chromosome = random.sample(range(len(performance_matrix)), 10)

    return chromosome

def crossover(parent1: list[int], parent2: list[int], points: int = 1) -> list[int]:
    """
    Returns a child from two parents using either one-point or two-points crossover.

    Args:
        parent1 (list): First parent chromosome.
        parent2 (list): Second parent chromosome.
        points (int, optional): The number of crossover points. Valid values are 1 or 2. Defaults to 1.

    Returns:
        list: A list representing the child chromosome created from the crossover.
    """

    # Check that point value is valid
    if points not in [1,2]:
        raise ValueError("Points argument must be either 1 or 2.")
    
    # Check that parents are same length, avoid potential index out of range errors.
    if len(parent1) != len(parent2):
        raise AttributeError(f"Length of parents are different: parent 1 {len(parent1)}, parent 2: {len(parent2)}")

    if points == 1:
        # One-point crossover
        crossover_point = random.randint(1, len(parent1) - 1) # Avoid 0 or len as the crossover point
        child = parent1[:crossover_point] + parent2[crossover_point:]
    
    if points == 2:
        # Two-point crossover
        # While loop to ensure there is no duplicate int generated
        crossover_point1, crossover_point2 = 0, 0
        while crossover_point1 == crossover_point2:
            crossover_point1 = random.randint(1, len(parent1) - 1)
            crossover_point2 = random.randint(1, len(parent1) - 1)

        # form child with parent2 center
        child = parent1[:crossover_point1] + parent2[crossover_point1:crossover_point2] + parent1[crossover_point2:]

    return child

def mutation(chromosome: list[int], num_employees: int = 13) -> list[int]:
    """
    Makes a small change to one of the values in the list.

    Args:
        chromosome (list[int]): A list of integers representing the tasks (index) and the employees assigned (value).
        num_employees (int): Number of employees in population. Defaults to 13 - the number of employees in PERFORMANCE_MATRIX  

    Returns: 
        list[int]: The mutated list.
    """
    # Random mutation choice
    mutation_type = random.choice(["swap", "replace"])

    if mutation_type == "swap":
        # Swap Mutation -> Select two random incidies (tasks) and swap the values (employees)

        indx1, indx2 = random.sample(range(len(chromosome)), 2)
        chromosome[indx1], chromosome[indx2] = chromosome[indx2], chromosome[indx1]

    elif mutation_type == "replace":
        # Replace Mutation -> Selects a random index (task) and replaces with an unassigned employee (value)

        # Get random index (employee) to replace
        emp_to_replace = random.randint(0, len(chromosome) - 1)

        # Get a random employee that is NOT currently assigned
        current_employees = set(chromosome)
        all_employees = set(range(num_employees))
        unassigned_employees = list(all_employees - current_employees)

        new_employee = random.choice(unassigned_employees)
        chromosome[emp_to_replace] = new_employee
        
    return chromosome


